const SET_USER_DETAILS = "SET_USER_DETAILS";
const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";
const SET_APP_LOADED='SET_APP_LOADED'
export { SET_USER_DETAILS, UPDATE_USER_DETAILS, REMOVE_USER_DETAILS,SET_APP_LOADED };
